var child = [
  { 'dupe': false, 'type': 16, 'name': 'errors.php', 'dir': 'c0', 'linked': 0, 'url': 'http://127.0.0.1:8000/errors.php', 'fetched': true, 'code': 200, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': false, 'type': 16, 'name': 'history.php', 'dir': 'c1', 'linked': 0, 'url': 'http://127.0.0.1:8000/history.php', 'fetched': true, 'code': 200, 'len': 233, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': false, 'type': 16, 'name': 'index.php', 'dir': 'c2', 'linked': 2, 'url': 'http://127.0.0.1:8000/index.php', 'fetched': true, 'code': 200, 'len': 453, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x6b4bd6f4 },
  { 'dupe': false, 'type': 16, 'name': 'login.php', 'dir': 'c3', 'linked': 5, 'url': 'http://127.0.0.1:8000/login.php', 'fetched': true, 'code': 200, 'len': 750, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 4, 'issue_cnt': [ 5, 0, 0, 0, 0 ], 'sig': 0xaf7d707a },
  { 'dupe': false, 'type': 16, 'name': 'register.php', 'dir': 'c4', 'linked': 5, 'url': 'http://127.0.0.1:8000/register.php', 'fetched': true, 'code': 200, 'len': 1009, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 6, 'issue_cnt': [ 7, 0, 0, 2, 0 ], 'sig': 0xcd903045 },
  { 'dupe': true, 'type': 16, 'name': 'server.php', 'dir': 'c5', 'linked': 0, 'url': 'http://127.0.0.1:8000/server.php', 'fetched': true, 'code': 200, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': false, 'type': 16, 'name': 'style.css', 'dir': 'c6', 'linked': 2, 'url': 'http://127.0.0.1:8000/style.css', 'fetched': true, 'code': 200, 'len': 1611, 'decl_mime': 'text/css', 'sniff_mime': 'text/css', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xc620abbe },
  { 'dupe': false, 'type': 16, 'name': 'transfer.php', 'dir': 'c7', 'linked': 0, 'url': 'http://127.0.0.1:8000/transfer.php', 'fetched': true, 'code': 200, 'len': 161, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff }
];
